### ISSUE TITLE
Belt Level

### ISSUE THREAD

**Issue by SenseiJoe** [dxc-technology/about-devops-dojo#60]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Being an actual Dojo owner, maybe consider changing the colors.
If you add one more level, you could follow the BJJ belt colors, white, blue, purple brown, black.
Most other dojo's would have about 10 belt levels.

**Comment by PhilippeBerthonneau-v35334** [comment]
Hi Joe

Thanks for taking the courses!

You are right: we do not track your completion. 
Internally at DXC though, we include such modules in courses and people seek for a badge then want to complete all and I guess in order.

Here on the internet, people are less engaged maybe, and just pick one module because they already know some concepts covered by others. Then I recently highlighted the dependencies in the introduction so that people know that they have to run other modules prior the one they picked.

Your specific problem may arise because we added new modules each has a lot to read then people need to come back later to continue. We haven't thought to that to be honest, like a gamification making the next module accessible once you have completed the previous one.

We welcome contributions from everyone: whether this is to propose a complete module (source is [here](https://github.com/dxc-technology/online-devops-dojo/blob/master/README.md)) or a just content without the lab part, or even add cookies to these static pages to tag the modules completed.

Enjoy the next modules of the Dojo 🎉

**Comment by PhilippeBerthonneau-v35334** [comment]
Actually internally at DXC we already associated a color to each type DevOps training: white, yellow, green, black.
The Online DevOps Dojo modules fit in yellow belt first stripe. You can find several presentations made in DevOps conferences like [this one](https://www.youtube.com/watch?v=5ejcK1sTv6k).
