### ISSUE TITLE
Keeping track of modules completed

### ISSUE THREAD

**Issue by SenseiJoe** [dxc-technology/about-devops-dojo#61]
Is your system keeping track of completed modules?
I've done the welcome & leading change modules but nowhere do I see what I've completed and if I click into "Leading Change" again it just wants me to do it again.

BTW: I love this idea, I talked about doing something like this a while ago but never got off my butt to do anything about it.
I would like to get blessing from my company for this to be a requirement for all devs in my company.  ( I of course need to complete it first)

**Comment by PhilippeBerthonneau-v35334** [comment]
Hi Joe

Thanks for taking the courses!

You are right: we do not track your completion. 
Internally at DXC though, we include such modules in courses and people seek for a badge then want to complete all and I guess in order.

Here on the internet, people are less engaged maybe, and just pick one module because they already know some concepts covered by others. Then I recently highlighted the dependencies in the introduction so that people know that they have to run other modules prior the one they picked.

Your specific problem may arise because we added new modules each has a lot to read then people need to come back later to continue. We haven't thought to that to be honest, like a gamification making the next module accessible once you have completed the previous one.

We welcome contributions from everyone: whether this is to propose a complete module (source is [here](https://github.com/dxc-technology/online-devops-dojo/blob/master/README.md)) or a just content without the lab part, or even add cookies to these static pages to tag the modules completed.

Enjoy the next modules of the Dojo 🎉
